apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hpa.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - kyverno.yaml
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
